apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels: { app: github-runner }
  template:
    metadata:
      labels: { app: github-runner }
    spec:
      serviceAccountName: ci-runner
      containers:
        - name: runner
          image: 192.168.3.49:30500/actions-runner:latest
          imagePullPolicy: Always
          env:
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef: { name: github-pat, key: token }
            - name: GITHUB_REPO
              value: qpmstudio/sre_demo
            - name: HTTP_PROXY
              value: http://192.168.3.155:7890
            - name: HTTPS_PROXY
              value: http://192.168.3.155:7890
            - name: NO_PROXY
              value: 192.168.3.49,localhost,127.0.0.1,.svc,.cluster.local
